apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  schedulerName: scheduler-plugins-scheduler
  containers:
  - name: workload
    image: yolo11:latest
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"