apiVersion: v1
kind: Pod
metadata:
  name: yolo11-test
spec:
  schedulerName: scheduler-plugins-controller
  containers:
  - name: yolo11
    image: yolo11:latest
    #resources:
      #limits:
        #cpu: "2000m"
        #memory: "4096Mi"